<h1 align = 'center'>Pandas Library</h1>

In [1]:
import pandas as pd
from pandas import Series

<h3 style = 'color:green'>Attributes In Series</h3>
    Series contains two things :<br>
     1.Attibutes<br>
     2.Methods

In [2]:
sr1 = Series([10,20,30,40])
sr1.values

array([10, 20, 30, 40])

In [3]:
sr1.head

<bound method NDFrame.head of 0    10
1    20
2    30
3    40
dtype: int64>

In [4]:
sr1.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
sr1.dtype

dtype('int64')

In [6]:
sr1.size

4

In [7]:
30 in sr1.values

True

<h2 style = 'color:Green'>Methods in Series</h2>
    Here 's' refers to Series object<br>
    1. s.head() - It gives the starting 5 values default.<br>
    2. s.tail() - It gives the ending 5 values default.<br>
    3. s.sum()  - It adds all the values in the series.<br>
    4. s.count() - It counts the number of values excluding 'NAN'/null values.<br>
    5. s.mean() - It gives the average value based on this column.<br>
    6. s.describe() - It gives various mathematical statistic results.<br>
    7. s.min() - It gives the minimum value in the column.<br>
    8. s.max() - It gives the maximum value in the column.<br>
    9. s.unique() - It gives all the unique values in a array format not in list format.<br>
    10. s.nunique() - It is Used to count the numberof unique values.

In [8]:
sr1.head()

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
sr1.tail(2)

2    30
3    40
dtype: int64

In [10]:
sr1.sum()

np.int64(100)

In [11]:
samp = [2,None,3,None,None,5]
sr2 = Series(samp)
sr2.count()

np.int64(3)

In [12]:
sr1.mean()

np.float64(25.0)

In [13]:
sr1.describe()

count     4.000000
mean     25.000000
std      12.909944
min      10.000000
25%      17.500000
50%      25.000000
75%      32.500000
max      40.000000
dtype: float64

In [14]:
sr1.min()

10

In [15]:
sr1.max()

40

In [16]:
l = [10,20,20,10,30,43,50,50,10]
sr3 = Series(l)
print(sr3)

0    10
1    20
2    20
3    10
4    30
5    43
6    50
7    50
8    10
dtype: int64

In [17]:
sr3.unique()

array([10, 20, 30, 43, 50])

In [18]:
sr3.nunique()

5

<h1 align = 'center'>About DataFrame</h1>

Dataframe is a data structures. Used to store multiple data values.
1. It can be created as empty dataframe.<br>
2. It can be created by using single list, Nested list , dictionary and so on.<br>

In [19]:
from pandas import DataFrame

In [20]:
marks = [10,20,30,40,50]  #single list is used to create a dataframe
marks_df = DataFrame(marks)
print(marks_df)

    0
0  10
1  20
2  30
3  40
4  50

In [21]:
marks2 = [['Vijay',90],                          #Nested List is used in this.
          ['Durga',91],
          ['Rao',94]
         ]
mark2_df = DataFrame(marks2)
print(mark2_df)

       0   1
0  Vijay  90
1  Durga  91
2    Rao  94

In [22]:
details = {'Names':['Vijay','Durga','Rao'],        #Dictionary is used in this.
          'Age':[23,21,22]
          }
details_df = DataFrame(details)
print(details_df)

   Names  Age
0  Vijay   23
1  Durga   21
2    Rao   22

In [23]:
mark2_df.columns = ['Name', 'Marks']  #naming the columns
print(mark2_df)

    Name  Marks
0  Vijay     90
1  Durga     91
2    Rao     94

In [24]:
mark2_df.rename(columns={'Marks':'marks_secured'}, inplace = True)  #Naming to a specific column
print(mark2_df)

    Name  marks_secured
0  Vijay             90
1  Durga             91
2    Rao             94

In [25]:
id1 = [i for i in range(1,4)]
details_df.index = id1
print(details_df)

   Names  Age
1  Vijay   23
2  Durga   21
3    Rao   22

<h2 style = 'color: Green'>Loading data from different files</h2>
1. pd.read_csv(file.csv) -> It loads the data in the csv file.<br>
2. pd.read_excel(file.xlsx) -> It loads the data in the excel file.<br>
3. pd.read_json(file.tsv) -> It loads the data in the json file.<br>
4. pd.read_table(file.tsv) -> It loads the data in the tsv file.(TSV means tab seperated )<br>
5. pd.read_html(url) - >

In [26]:
import requests            #Future Proof Version Web Scraping
from io import StringIO

header = {"User-Agent":"Mozilla"}
url = "https://en.wikipedia.org/wiki/The_World%27s_Billionaires"
response = requests.get(url, headers = header)

a = pd.read_html(StringIO(response.text))

print(a[3])

   No.                      Name Net worth (USD)  Age  \
0    1  Bernard Arnault & family    $233 billion   75
1    2                 Elon Musk    $195 billion   52
2    3                Jeff Bezos    $194 billion   60
3    4           Mark Zuckerberg    $177 billion   39
4    5             Larry Ellison    $141 billion   79
5    6            Warren Buffett    $133 billion   93
6    7                Bill Gates    $128 billion   68
7    8             Steve Ballmer    $121 billion   68
8    9             Mukesh Ambani    $116 billion   66
9   10                Larry Page    $114 billion   51

                           Nationality Primary source(s) of wealth
0                               France                        LVMH
1  South Africa  Canada  United States               Tesla, SpaceX
2                        United States                      Amazon
3                        United States              Meta Platforms
4                        United States          Oracle Corporation
5                        United States          Berkshire Hathaway
6                        United States                   Microsoft
7                        United States                   Microsoft
8                                India         Reliance Industries
9                        United States                      Google

<h3 style = 'color:green'>DataFrame Attributes</h3>
1. df.shape - It gives the total number of rows and columns.<br>
2. df.columns - It gives column headings/names in a index_list.<br>
3. df.size - It gives total sumarized values all rows and columns.<br>
4. df.dtypes - It gives the data type of each column values.<br>
5. df.empty - It checks whether dataframe is empty or not.<br>
6. df.index - It gives the range of the index.<br>
7. df.values - It converts dataframe into an array for faster execution.<br>
8. df.T - It transpose the data in the dataframe as  rows into columns and columns into rows.<br>

In [27]:
data = pd.read_csv('D:\Datasets\shadowfax_delivery_dataset.csv')
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [28]:
len(data)

5000

In [29]:
data.shape

(5000, 10)

In [30]:
data.columns

Index(['order_id', 'partner_id', 'customer_id', 'city', 'distance_km',
       'delivery_time_min', 'scheduled_time_min', 'order_value', 'rating',
       'delay_flag'],
      dtype='object')

In [31]:
data.size

50000

In [32]:
data.dtypes

order_id                int64
partner_id              int64
customer_id             int64
city                   object
distance_km           float64
delivery_time_min     float64
scheduled_time_min    float64
order_value           float64
rating                  int64
delay_flag              int64
dtype: object

In [33]:
data.empty

False

In [34]:
data.index

RangeIndex(start=0, stop=5000, step=1)

In [35]:
data.values

array([[1, 103, 1141, ..., 187.89, 2, 0],
       [2, 271, 271, ..., 401.45, 2, 0],
       [3, 107, 770, ..., 596.3, 4, 1],
       ...,
       [4998, 161, 270, ..., 551.81, 4, 0],
       [4999, 235, 1574, ..., 1308.71, 1, 1],
       [5000, 190, 396, ..., 1441.53, 4, 1]],
      shape=(5000, 10), dtype=object)

In [36]:
data.T

,0,1,2,3,4,5,6,7,8,9,...,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999
order_id,1,2,3,4,5,6,7,8,9,10,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,5000
partner_id,103,271,107,72,189,21,103,122,215,88,...,229,12,118,155,246,247,29,161,235,190
customer_id,1141,271,770,1716,1511,1909,172,1974,274,259,...,439,1156,1891,382,138,943,843,270,1574,396
city,Chennai,Mumbai,Bangalore,Delhi,Bangalore,Chennai,Mumbai,Bangalore,Chennai,Delhi,...,Mumbai,Mumbai,Bangalore,Hyderabad,Delhi,Chennai,Hyderabad,Bangalore,Hyderabad,Bangalore
distance_km,5.7,19.36,3.62,15.85,19.69,0.89,14.13,5.43,1.29,8.36,...,2.52,9.43,7.83,11.76,9.05,0.84,19.88,11.1,9.74,19.12
delivery_time_min,27.1,30.8,98.9,38.7,97.9,39.9,13.7,66.9,31.6,93.4,...,41.0,11.6,23.0,106.5,102.0,42.5,41.4,97.2,113.2,95.7
scheduled_time_min,74.5,41.8,67.3,41.0,92.7,54.8,95.0,54.3,94.2,50.0,...,104.9,65.1,77.2,76.2,31.9,55.1,83.6,107.5,35.1,56.9
order_value,187.89,401.45,596.3,833.93,384.32,379.97,1177.85,1445.83,519.24,1047.59,...,833.3,125.06,1019.36,446.05,78.56,146.33,1438.06,551.81,1308.71,1441.53
rating,2,2,4,3,3,5,5,3,3,3,...,1,5,4,3,3,3,4,4,1,4
delay_flag,0,0,1,0,1,0,0,1,0,1,...,0,0,0,1,1,0,0,0,1,1

<h3 style = 'color : green'>DataFrame Methods</h3>
1. df.head() - It gives top five rows.<br>
2. df.tail() - It gives last five rows.<br>
3. df.info() - It gives the information about all the columns.<br>
4. df.count() - It counts all the non-null values and skips null values in every column.<br>
5. df.describe() - It gives statistical values.<br>
6. df.nunique() - It gives the count of unique values in every column.<br>

In [37]:
data.head()

,order_id,partner_id,customer_id,city,distance_km,delivery_time_min,scheduled_time_min,order_value,rating,delay_flag
0,1,103,1141,Chennai,5.70,27.1,74.5,187.89,2,0
1,2,271,271,Mumbai,19.36,30.8,41.8,401.45,2,0
2,3,107,770,Bangalore,3.62,98.9,67.3,596.30,4,1
3,4,72,1716,Delhi,15.85,38.7,41.0,833.93,3,0
4,5,189,1511,Bangalore,19.69,97.9,92.7,384.32,3,1

In [38]:
data.tail()

,order_id,partner_id,customer_id,city,distance_km,delivery_time_min,scheduled_time_min,order_value,rating,delay_flag
4995,4996,247,943,Chennai,0.84,42.5,55.1,146.33,3,0
4996,4997,29,843,Hyderabad,19.88,41.4,83.6,1438.06,4,0
4997,4998,161,270,Bangalore,11.10,97.2,107.5,551.81,4,0
4998,4999,235,1574,Hyderabad,9.74,113.2,35.1,1308.71,1,1
4999,5000,190,396,Bangalore,19.12,95.7,56.9,1441.53,4,1

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            5000 non-null   int64
 1   partner_id          5000 non-null   int64
 2   customer_id         5000 non-null   int64
 3   city                5000 non-null   object
 4   distance_km         5000 non-null   float64
 5   delivery_time_min   5000 non-null   float64
 6   scheduled_time_min  5000 non-null   float64
 7   order_value         5000 non-null   float64
 8   rating              5000 non-null   int64
 9   delay_flag          5000 non-null   int64
dtypes: float64(4), int64(5), object(1)
memory usage: 390.8+ KB

In [40]:
data.count()

order_id              5000
partner_id            5000
customer_id           5000
city                  5000
distance_km           5000
delivery_time_min     5000
scheduled_time_min    5000
order_value           5000
rating                5000
delay_flag            5000
dtype: int64

In [41]:
data.nunique()

order_id              5000
partner_id             300
customer_id           1850
city                     6
distance_km           1782
delivery_time_min     1086
scheduled_time_min     900
order_value           4905
rating                   5
delay_flag               2
dtype: int64

In [42]:
data["order_value"]

0        187.89
1        401.45
2        596.30
3        833.93
4        384.32
         ...
4995     146.33
4996    1438.06
4997     551.81
4998    1308.71
4999    1441.53
Name: order_value, Length: 5000, dtype: float64

<h3 style = "color : blue">Accessing single column in a dataframe</h3>
There are Two types to do this:<br>
1. df.column_name      -->    Not Recommended But Works.<br>
2. df["column_name"]   -->    highly recommended.<br>

In [43]:
data.city

0         Chennai
1          Mumbai
2       Bangalore
3           Delhi
4       Bangalore
          ...
4995      Chennai
4996    Hyderabad
4997    Bangalore
4998    Hyderabad
4999    Bangalore
Name: city, Length: 5000, dtype: object

In [44]:
data["city"]

0         Chennai
1          Mumbai
2       Bangalore
3           Delhi
4       Bangalore
          ...
4995      Chennai
4996    Hyderabad
4997    Bangalore
4998    Hyderabad
4999    Bangalore
Name: city, Length: 5000, dtype: object

<h3 style = "color : Blue">Accessing desired number column from a datafra</h3>

In [45]:
col = ["city","order_id"]
data[col]

           city  order_id
0       Chennai         1
1        Mumbai         2
2     Bangalore         3
3         Delhi         4
4     Bangalore         5
...         ...       ...
4995    Chennai      4996
4996  Hyderabad      4997
4997  Bangalore      4998
4998  Hyderabad      4999
4999  Bangalore      5000

[5000 rows x 2 columns]

In [46]:
col = ["city","order_id"]
data[col].head()

        city  order_id
0    Chennai         1
1     Mumbai         2
2  Bangalore         3
3      Delhi         4
4  Bangalore         5

<h3 style = "color : Blue">Renaming and changing columns,Index and so on!</h3>

In [47]:
data.columns

Index(['order_id', 'partner_id', 'customer_id', 'city', 'distance_km',
       'delivery_time_min', 'scheduled_time_min', 'order_value', 'rating',
       'delay_flag'],
      dtype='object')

In [48]:
data.rename(columns = {"city":"location"})

,order_id,partner_id,customer_id,location,distance_km,delivery_time_min,scheduled_time_min,order_value,rating,delay_flag
0,1,103,1141,Chennai,5.70,27.1,74.5,187.89,2,0
1,2,271,271,Mumbai,19.36,30.8,41.8,401.45,2,0
2,3,107,770,Bangalore,3.62,98.9,67.3,596.30,4,1
3,4,72,1716,Delhi,15.85,38.7,41.0,833.93,3,0
4,5,189,1511,Bangalore,19.69,97.9,92.7,384.32,3,1
...,...,...,...,...,...,...,...,...,...,...
4995,4996,247,943,Chennai,0.84,42.5,55.1,146.33,3,0
4996,4997,29,843,Hyderabad,19.88,41.4,83.6,1438.06,4,0
4997,4998,161,270,Bangalore,11.10,97.2,107.5,551.81,4,0
4998,4999,235,1574,Hyderabad,9.74,113.2,35.1,1308.71,1,1
4999,5000,190,396,Bangalore,19.12,95.7,56.9,1441.53,4,1

In [49]:
data2 = data.rename(index = {0:11})
data2

,order_id,partner_id,customer_id,city,distance_km,delivery_time_min,scheduled_time_min,order_value,rating,delay_flag
11,1,103,1141,Chennai,5.70,27.1,74.5,187.89,2,0
1,2,271,271,Mumbai,19.36,30.8,41.8,401.45,2,0
2,3,107,770,Bangalore,3.62,98.9,67.3,596.30,4,1
3,4,72,1716,Delhi,15.85,38.7,41.0,833.93,3,0
4,5,189,1511,Bangalore,19.69,97.9,92.7,384.32,3,1
...,...,...,...,...,...,...,...,...,...,...
4995,4996,247,943,Chennai,0.84,42.5,55.1,146.33,3,0
4996,4997,29,843,Hyderabad,19.88,41.4,83.6,1438.06,4,0
4997,4998,161,270,Bangalore,11.10,97.2,107.5,551.81,4,0
4998,4999,235,1574,Hyderabad,9.74,113.2,35.1,1308.71,1,1
4999,5000,190,396,Bangalore,19.12,95.7,56.9,1441.53,4,1

In [50]:
data.columns.str.upper()

Index(['ORDER_ID', 'PARTNER_ID', 'CUSTOMER_ID', 'CITY', 'DISTANCE_KM',
       'DELIVERY_TIME_MIN', 'SCHEDULED_TIME_MIN', 'ORDER_VALUE', 'RATING',
       'DELAY_FLAG'],
      dtype='object')

<h3 style = "color : Green">DataFrame - Inplace Parameter</h3>
It prevents the creation of duplicate dataframe for the same dataframe using rename method.<br>
It replace the values istead of creating a duplicate dataframe.

In [51]:
n = {i:i+1 for i in range(0,5000)}
data.rename(index = n, inplace = True )
data

,order_id,partner_id,customer_id,city,distance_km,delivery_time_min,scheduled_time_min,order_value,rating,delay_flag
1,1,103,1141,Chennai,5.70,27.1,74.5,187.89,2,0
2,2,271,271,Mumbai,19.36,30.8,41.8,401.45,2,0
3,3,107,770,Bangalore,3.62,98.9,67.3,596.30,4,1
4,4,72,1716,Delhi,15.85,38.7,41.0,833.93,3,0
5,5,189,1511,Bangalore,19.69,97.9,92.7,384.32,3,1
...,...,...,...,...,...,...,...,...,...,...
4996,4996,247,943,Chennai,0.84,42.5,55.1,146.33,3,0
4997,4997,29,843,Hyderabad,19.88,41.4,83.6,1438.06,4,0
4998,4998,161,270,Bangalore,11.10,97.2,107.5,551.81,4,0
4999,4999,235,1574,Hyderabad,9.74,113.2,35.1,1308.71,1,1
5000,5000,190,396,Bangalore,19.12,95.7,56.9,1441.53,4,1

In [52]:
link = "D:\Datasets\startup_funding.csv"
start_up = pd.read_csv(link)
stp_df = DataFrame(start_up)
stp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [53]:
stp_df.isna().sum()        #It counts the missing values

Sr No                   0
Date dd/mm/yyyy         0
Startup Name            0
Industry Vertical     171
SubVertical           936
City  Location        180
Investors Name         24
InvestmentnType         4
Amount in USD         960
Remarks              2625
dtype: int64

In [54]:
s = stp_df.isna().sum()    #Percentage version
perc = (s/3044)*100
perc

Sr No                 0.000000
Date dd/mm/yyyy       0.000000
Startup Name          0.000000
Industry Vertical     5.617608
SubVertical          30.749014
City  Location        5.913272
Investors Name        0.788436
InvestmentnType       0.131406
Amount in USD        31.537451
Remarks              86.235217
dtype: float64

In [55]:
stp_df.isnull().head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,True

In [56]:
stp_df.notnull().head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,True,True,True,True,True,True,True,True,True,False
1,True,True,True,True,True,True,True,True,True,False
2,True,True,True,True,True,True,True,True,True,False
3,True,True,True,True,True,True,True,True,True,False
4,True,True,True,True,True,True,True,True,True,False

<h3 style = "color : Green">Pandas - Handling The Missing Values Or NAN Values</h3>
1. None --> It is used in python to represent "nothing".<br>
2. NaN --> It is used in pandas to represent missing values.<br>
3. inplace = True/False --> It is used to apply changes in the original frame.<br>

In [57]:
stp_df.dropna()  #It removes entire row if it have a single missing value.

Empty DataFrame
Columns: [Sr No, Date dd/mm/yyyy, Startup Name, Industry Vertical, SubVertical, City  Location, Investors Name, InvestmentnType, Amount in USD, Remarks]
Index: []

In [58]:
stp_df

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [59]:
stp_df.fillna(0)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",0
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",0
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",0
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",0
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",0
...,...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,0,0,0,Asia Pacific Internet Group,Private Equity,"45,00,000",0
3040,3041,29/01/2015,Graphene,0,0,0,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,0,0,0,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",0
3042,3043,30/01/2015,Simplotel,0,0,0,MakeMyTrip,Private Equity,0,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,0,0,0,UK based Group of Angel Investors,Seed Funding,"1,40,000",0

In [60]:
stp_df["Amount in USD"]
#need to fill the missing values with mean value.

0       20,00,00,000
1          80,48,394
2        1,83,58,860
3          30,00,000
4          18,00,000
            ...
3039       45,00,000
3040        8,25,000
3041       15,00,000
3042             NaN
3043        1,40,000
Name: Amount in USD, Length: 3044, dtype: object

1. df["column_name"].mean()
2. df["column_name"].median()
3. df.fillna()
4. df.isna().sum()
5. df.replace(value1,value2)

<h3 style = "color : green">Selection by using loc and iloc</h3>

In [61]:
stp_df.columns

Index(['Sr No', 'Date dd/mm/yyyy', 'Startup Name', 'Industry Vertical',
       'SubVertical', 'City  Location', 'Investors Name', 'InvestmentnType',
       'Amount in USD', 'Remarks'],
      dtype='object')

In [62]:
places = ["Mumbai","New Delhi"]
for city in places:
    mumb = stp_df["City  Location"] == city
    
    print(stp_df[mumb])

      Sr No Date dd/mm/yyyy  Startup Name            Industry Vertical  \
4         5      02/01/2020        Fashor          Fashion and Apparel
13       14      16/12/2019        InCred                      Finance
28       29      18/11/2019  Medikabazaar                   Healthcare
36       37      04/09/2019       Cashflo                      FinTech
37       38      04/09/2019    Digital F5       Advertising, Marketing
...     ...             ...           ...                          ...
2841   2842      18/04/2015      Doormint  On-Demand Handyman Services
2851   2852      23/04/2015  Craftstvilla     Ethnic Product eCommerce
2857   2858      24/04/2015      Coverfox  Online Insurance Aggregator
2859   2860      27/04/2015          Grab    Food Logistics & Delivery
2865   2866      28/04/2015   Naaptol.com    Tele-Shopping / eCommerce

                                            SubVertical City  Location  \
4                           Embroiled Clothes For Women         Mumbai
13                        Non-Banking Financial Company         Mumbai
28                    B2B platform for medical supplies         Mumbai
36    Invoice discounting platform and SME lending m...         Mumbai
37                               Digital marketing firm         Mumbai
...                                                 ...            ...
2841                                                NaN         Mumbai
2851                                                NaN         Mumbai
2857                                                NaN         Mumbai
2859                                                NaN         Mumbai
2865                                                NaN         Mumbai

                                         Investors Name       InvestmentnType  \
4                               Sprout Venture Partners            Seed Round
13                                                  NaN          Debt Funding
28    Ackermans & van Haaren, HealthQuad, Rebright P...              Series B
36                                        SAIF Partners              Series A
37                                   TIW Private Equity  Private Equity Round
...                                                 ...                   ...
2841                                Powai Lake Ventures          Seed Funding
2851  Sequoia Capital, Nexus venture Partners, Light...        Private Equity
2857              Accel US, Accel India, SAIF Partners.        Private Equity
2859                    Oliphans Capital, Haresh Chawla          Seed Funding
2865                   Mitsui & Co & existing investors        Private Equity

     Amount in USD   Remarks
4        18,00,000       NaN
13       59,00,000       NaN
28     1,58,00,000       NaN
36       33,00,000       NaN
37       60,00,000       NaN
...            ...       ...
2841           NaN       NaN
2851   1,80,00,000  Series B
2857   1,20,00,000  Series B
2859     10,00,000       NaN
2865   2,15,00,000  Series C

[567 rows x 10 columns]
      Sr No Date dd/mm/yyyy                  Startup Name  \
3         4      02/01/2020  https://www.wealthbucket.in/
45       46      01/08/2019                       Progcap
63       64      01/07/2019                    WizCounsel
66       67      04/07/2019        Daalchini Technologies
75       76      04/06/2019                        Bira91
...     ...             ...                           ...
2847   2848      22/04/2015                     FindYahan
2849   2850      22/04/2015               Avanti Learning
2855   2856      23/04/2015                     EazyDiner
2856   2857      23/04/2015                 Phone Warrior
2861   2862      27/04/2015                         GIBBS

                    Industry Vertical              SubVertical City  Location  \
3                             FinTech        Online Investment      New Delhi
45                            Finance  Supply Chain Management      New Delhi
63                         Compliance               Consulting      New Delhi
66                  Food and Beverage  Digital Vending Machine      New Delhi
75                  Food and Beverage                  Brewery      New Delhi
...                               ...                      ...            ...
2847  Hyperlocal services marketplace                      NaN      New Delhi
2849         Private Coaching Centers                      NaN      New Delhi
2855       Restaurant reservation app                      NaN      New Delhi
2856              Spam Call block App                      NaN      New Delhi
2861                       Clean Tech                      NaN      New Delhi

                                         Investors Name InvestmentnType  \
3                                        Vinod Khatumal    Pre-series A
45                                        Sequoia India        Series A
63                                            Kapil Dev           Angel
66                                        Artha Venture      Seed Round
75                                       Anicut Capital    Debt Funding
...                                                 ...             ...
2847                                   The Phoenix Fund  Private Equity
2849  Michael & Susan Dell Foundation, Pearson Learn...  Private Equity
2855                 Deepak Shahdadpuri, Gulpreet Kohli    Seed Funding
2856                                Lightspeed Ventures    Seed Funding
2861                               Infuse Ventures fund  Private Equity

     Amount in USD       Remarks
3        30,00,000           NaN
45       50,00,000           NaN
63        1,45,000           NaN
66        5,00,000           NaN
75     1,00,00,000           NaN
...            ...           ...
2847           NaN      Series A
2849     15,00,000      Series A
2855           NaN           NaN
2856           NaN  Pre-Series A
2861           NaN      Series B

[421 rows x 10 columns]

In [63]:
fund_type = stp_df["InvestmentnType"] == "Seed Funding"
stp_df[fund_type]

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
24,25,12/11/2019,SuperGaming,Video Games,Social gaming platform,Pune,Dream Incubator,Seed Funding,"13,00,000",NaN
27,28,19/11/2019,Digital Mall Asia,E-Commerce,Virtual e-commerce platform,Delhi,Amour Infrastructure,Seed Funding,"22,00,00,000",NaN
84,85,10/06/2019,Bolo App,Digital Media,Video Platform,Bengaluru,Nexus Venture Partners,Seed Funding,"4,30,200",NaN
102,103,12/04/2019,Azah,Health and Wellness,Organic wellness,Gurugram,Unnamed angel investors,Seed Funding,"2,00,000",NaN
103,104,11/04/2019,Setu,Fintech,Banking,Bengaluru,Lightspeed India Partners,Seed Funding,"35,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3028,3029,21/05/2015,Villgro,NaN,NaN,NaN,Michael & Susan Dell Foundation,Seed Funding,"32,50,000",To fund edu startups
3029,3030,22/01//2015,Corporate360,NaN,NaN,NaN,Group of Angel Investors,Seed Funding,"2,00,000",NaN
3030,3031,22/01/2015,Freshmonk,NaN,NaN,NaN,"August Capital Partners, Michael Blakey",Seed Funding,NaN,NaN
3034,3035,24/01/2015,Aasaanjobs,NaN,NaN,NaN,"Inventus Capital Partners, IDG Ventures",Seed Funding,"15,00,000",NaN
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

<h3 style = "color : orange">loc and iloc is also called as indexers</h3>
<h4 style = "color : green">1. iloc </h4> 
--> It is used to locate the index of the row.<br>
--> It only takes integer as a value apart from other input it throws error.<br>
--> It operates fast than normal operators interms of performance speed.<br>
<h4 style = "color : green">2. loc </h4> 
--> It is used to locate a specific values.<br>
--> It is used after changing index with a column.<br>
--> It is very fast in processing.<br>

In [64]:
stp_df.iloc[1]

Sr No                                        2
Date dd/mm/yyyy                     13/01/2020
Startup Name                            Shuttl
Industry Vertical               Transportation
SubVertical          App based shuttle service
City  Location                         Gurgaon
Investors Name       Susquehanna Growth Equity
InvestmentnType                       Series C
Amount in USD                        80,48,394
Remarks                                    NaN
Name: 1, dtype: object

In [65]:
stp_df.iloc[1,2]

'Shuttl'

In [66]:
stp_df.iloc[:,:]   #To view entire dataset/dataframe

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [67]:
stp_df.iloc[:,2]             #To view a specific column in the dataframe

0                             BYJU’S
1                             Shuttl
2                          Mamaearth
3       https://www.wealthbucket.in/
4                             Fashor
                    ...
3039                      Printvenue
3040                        Graphene
3041                  Mad Street Den
3042                       Simplotel
3043                couponmachine.in
Name: Startup Name, Length: 3044, dtype: object

In [68]:
stp_df.iloc[1:3,2:4]       #Limiting rows and columns

  Startup Name Industry Vertical
1       Shuttl    Transportation
2    Mamaearth        E-commerce

In [69]:
stp_df.set_index("Industry Vertical", inplace = True)    #it changes column into index

In [70]:
ids1 = ["Transportation","E-Tech","Fintech","E-commerce"]
stp_df.loc[ids1]

,Sr No,Date dd/mm/yyyy,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
Industry Vertical,,,,,,,,,
Transportation,2,13/01/2020,Shuttl,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
Transportation,61,27/08/2019,Rapido Bike Taxi,Bike Taxi,Bengaluru,Westbridge Capital,Series B,"3,90,00,00,000",NaN
Transportation,88,08/06/2019,Vogo Automotive Pvt. Ltd.,Dockless Scooter Rental Company,Karnataka,Alteria Capital,Debt Funding,"35,84,000",NaN
Transportation,111,17/04/2019,Shuttl,Bus Aggregation,Gurugram,New Atlantic Ventures,Venture Round,"50,00,000",NaN
E-Tech,1,09/01/2020,BYJU’S,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
Fintech,104,11/04/2019,Setu,Banking,Bengaluru,Lightspeed India Partners,Seed Funding,"35,00,000",NaN
E-commerce,3,09/01/2020,Mamaearth,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
E-commerce,92,05/05/2019,StyleDotMe,Fashion and Shopping,Delhi,Indian Angel Network and other angel investors...,Bridge Round,undisclosed,NaN
E-commerce,97,30/05/2019,GlowRoad,Retail,Bengaluru,"Korea Investment Partners, Vertex Ventures",Series B,"1,15,00,000",NaN
E-commerce,100,12/04/2019,Medlife,Online Medicine,Bengaluru,Prasid Uno Family Trust,Private Equity,"1,70,00,000",NaN
E-commerce,101,10/04/2019,Kabadiwala,Waste Management,Bhopal,"Unilever, Beehive Capital Advisor, ABCOM Inves...",Private Equity,"4,30,665",NaN
E-commerce,106,10/04/2019,Craftsvilla,Fashion and Apparel,Mumbai,Supera Pte Ltd,Inhouse Funding,"24,43,495",NaN
E-commerce,109,19/04/2019,My Healthcare,Software Solutions,Bengaluru and Gurugram,Sixth Sense Ventures,Series A,"30,00,000",NaN
E-commerce,110,19/04/2019,KrazyBee,Lending Platform,Bengaluru,"BAC Acquisitions, Unifi AIF, BRD Securities, N...",Debt,"14,342,000+",NaN
E-commerce,394,05/01/2018,WOTU,Food and Beverages,Bengaluru,"Claris Capital, Mumbai Angels Network",Angel / Seed Funding,NaN,NaN
E-commerce,395,08/01/2018,DAAKI,Sports Nutrition Supplement etailer,Bengaluru,Rohan Agila,Angel / Seed Funding,NaN,NaN
E-commerce,399,10/01/2018,Appario Retail Pvt Ltd.,Retail,Delhi,Amazon-Patni JV,Private Equity,"1,88,40,000",NaN
E-commerce,414,23/01/2018,Milkbasket,Online Grocery,Gurugram,Unilever Ventures,Private Equity,"30,00,000",NaN

In [71]:
a = ["Fashion and Apparel","Transportation","E-Tech","Fintech","E-commerce"]
b = ["City  Location","Startup Name"]
stp_df.loc[a,b]

                             City  Location               Startup Name
Industry Vertical
Fashion and Apparel                  Mumbai                     Fashor
Transportation                      Gurgaon                     Shuttl
Transportation                    Bengaluru           Rapido Bike Taxi
Transportation                    Karnataka  Vogo Automotive Pvt. Ltd.
Transportation                     Gurugram                     Shuttl
E-Tech                            Bengaluru                     BYJU’S
Fintech                           Bengaluru                       Setu
E-commerce                        Bengaluru                  Mamaearth
E-commerce                            Delhi                 StyleDotMe
E-commerce                        Bengaluru                   GlowRoad
E-commerce                        Bengaluru                    Medlife
E-commerce                           Bhopal                 Kabadiwala
E-commerce                           Mumbai                Craftsvilla
E-commerce           Bengaluru and Gurugram              My Healthcare
E-commerce                        Bengaluru                   KrazyBee
E-commerce                        Bengaluru                       WOTU
E-commerce                        Bengaluru                      DAAKI
E-commerce                            Delhi    Appario Retail Pvt Ltd.
E-commerce                         Gurugram                 Milkbasket

<h2 style = "color : orange">Pandas DataFrame Filtering</h2>

In [72]:
stp_df[stp_df["InvestmentnType"] == "Private Equity"]

,Sr No,Date dd/mm/yyyy,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
Industry Vertical,,,,,,,,,
E-commerce,100,12/04/2019,Medlife,Online Medicine,Bengaluru,Prasid Uno Family Trust,Private Equity,"1,70,00,000",NaN
E-commerce,101,10/04/2019,Kabadiwala,Waste Management,Bhopal,"Unilever, Beehive Capital Advisor, ABCOM Inves...",Private Equity,"4,30,665",NaN
Finance,143,25/11/2018,InCred Finance,SME Lending,India,"Paragon Partners, Individual Investors",Private Equity,"4,20,00,000",NaN
Food,147,04/10/2018,Grover Zampa,Wine,Mumbai,Ravi Viswanathan,Private Equity,"82,00,000",NaN
Consumer Internet,152,01/09/2018,Netmeds,Online Pharmacy Chain,Chennai,"Sistema Asia Fund, Sistema JSFC and Tanncam In...",Private Equity,"3,50,00,000",NaN
...,...,...,...,...,...,...,...,...,...
NaN,3039,28/01/2015,Grabhouse.com,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,"25,00,000",Series A
NaN,3040,29/01/2015,Printvenue,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
NaN,3041,29/01/2015,Graphene,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
NaN,3042,30/01/2015,Mad Street Den,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
NaN,3043,30/01/2015,Simplotel,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"

In [73]:
stp_df[stp_df["Sr No"] < 500]

,Sr No,Date dd/mm/yyyy,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
Industry Vertical,,,,,,,,,
E-Tech,1,09/01/2020,BYJU’S,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
Transportation,2,13/01/2020,Shuttl,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
E-commerce,3,09/01/2020,Mamaearth,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
FinTech,4,02/01/2020,https://www.wealthbucket.in/,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
Fashion and Apparel,5,02/01/2020,Fashor,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...
Technology,495,14/11/2017,Active AI,AI based FinTech platform,Bangalore,Vertex Ventures,Private Equity,"82,50,000",NaN
Technology,496,15/11/2017,Sumeru,Banking Software License Platform,Bangalore,Undisclosed Investors,Seed Funding,"9,00,000",NaN
Health Care,497,15/11/2017,ElderAid Wellness,Social Healthcare Enterprise,Bangalore,Rugmini Menon,Angel Funding,NaN,NaN
Technology,498,15/11/2017,Omnia Information,WiFi Analytics Platform,Delhi,Omidyar Network,Private Equity,"30,00,000",NaN
Inspiration,499,15/11/2017,Josh Talks,Storytelling platform,Gurgaon,"Girish Mathrubootham, Apurva Chamaria, Rohit C...",Private Equity,NaN,NaN

In [74]:
filter1 = stp_df["City  Location"] == "Mumbai"
filter2 = stp_df["InvestmentnType"] == "Private Equity"
stp_df[filter1 & filter2]                                      # "&" using "AND" operator.

,Sr No,Date dd/mm/yyyy,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
Industry Vertical,,,,,,,,,
Food,147,04/10/2018,Grover Zampa,Wine,Mumbai,Ravi Viswanathan,Private Equity,"82,00,000",NaN
Consumer Internet,157,05/09/2018,Nykaa,Online Marketplace For Multi-brand Beauty Cosm...,Mumbai,Lighthouse,Private Equity,"15,72,00,000",NaN
Consumer Internet,159,06/09/2018,Dream11,Online Gaming Platform,Mumbai,"Tencent, Kalaari Capital and Private equity fi...",Private Equity,"10,00,00,000",NaN
Fin-Tech,163,11/09/2018,Upwards,Online Micro Lending Marketplace,Mumbai,"Shunwei Capital,Quotient, Mayfield & Others",Private Equity,"50,00,000",NaN
Fin-Tech,164,12/09/2018,Kissht,Online lending Platform,Mumbai,Vertex Ventures Southeast Asia (SEA) and India...,Private Equity,"3,00,00,000",NaN
...,...,...,...,...,...,...,...,...,...
Ed-Tech,2826,09/04/2015,Purple Squirrel,NaN,Mumbai,"Matrix Partners India, India Quotient",Private Equity,NaN,Series B
Hyper-local Online Services,2835,14/04/2015,LocalOye,NaN,Mumbai,"Tiger Global Management, Lightspeed Venture Pa...",Private Equity,"50,00,000",Series A
Ethnic Product eCommerce,2852,23/04/2015,Craftstvilla,NaN,Mumbai,"Sequoia Capital, Nexus venture Partners, Light...",Private Equity,"1,80,00,000",Series B
Online Insurance Aggregator,2858,24/04/2015,Coverfox,NaN,Mumbai,"Accel US, Accel India, SAIF Partners.",Private Equity,"1,20,00,000",Series B
Tele-Shopping / eCommerce,2866,28/04/2015,Naaptol.com,NaN,Mumbai,Mitsui & Co & existing investors,Private Equity,"2,15,00,000",Series C

In [75]:
filter1 = stp_df["City  Location"] == "Mumbai"
filter2 = stp_df["InvestmentnType"] == "Private Equity"      # "loc" is used here.
stp_df.loc[filter1 & filter2]                                # "&" using "AND" operator.

,Sr No,Date dd/mm/yyyy,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
Industry Vertical,,,,,,,,,
Food,147,04/10/2018,Grover Zampa,Wine,Mumbai,Ravi Viswanathan,Private Equity,"82,00,000",NaN
Consumer Internet,157,05/09/2018,Nykaa,Online Marketplace For Multi-brand Beauty Cosm...,Mumbai,Lighthouse,Private Equity,"15,72,00,000",NaN
Consumer Internet,159,06/09/2018,Dream11,Online Gaming Platform,Mumbai,"Tencent, Kalaari Capital and Private equity fi...",Private Equity,"10,00,00,000",NaN
Fin-Tech,163,11/09/2018,Upwards,Online Micro Lending Marketplace,Mumbai,"Shunwei Capital,Quotient, Mayfield & Others",Private Equity,"50,00,000",NaN
Fin-Tech,164,12/09/2018,Kissht,Online lending Platform,Mumbai,Vertex Ventures Southeast Asia (SEA) and India...,Private Equity,"3,00,00,000",NaN
...,...,...,...,...,...,...,...,...,...
Ed-Tech,2826,09/04/2015,Purple Squirrel,NaN,Mumbai,"Matrix Partners India, India Quotient",Private Equity,NaN,Series B
Hyper-local Online Services,2835,14/04/2015,LocalOye,NaN,Mumbai,"Tiger Global Management, Lightspeed Venture Pa...",Private Equity,"50,00,000",Series A
Ethnic Product eCommerce,2852,23/04/2015,Craftstvilla,NaN,Mumbai,"Sequoia Capital, Nexus venture Partners, Light...",Private Equity,"1,80,00,000",Series B
Online Insurance Aggregator,2858,24/04/2015,Coverfox,NaN,Mumbai,"Accel US, Accel India, SAIF Partners.",Private Equity,"1,20,00,000",Series B
Tele-Shopping / eCommerce,2866,28/04/2015,Naaptol.com,NaN,Mumbai,Mitsui & Co & existing investors,Private Equity,"2,15,00,000",Series C

In [76]:
filter1 = stp_df["City  Location"] == "Mumbai"
filter2 = stp_df["InvestmentnType"] == "Private Equity"
stp_df.loc[filter1 | filter2]                                 # "|" using it as "OR" operator

,Sr No,Date dd/mm/yyyy,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
Industry Vertical,,,,,,,,,
Fashion and Apparel,5,02/01/2020,Fashor,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
Finance,14,16/12/2019,InCred,Non-Banking Financial Company,Mumbai,NaN,Debt Funding,"59,00,000",NaN
Healthcare,29,18/11/2019,Medikabazaar,B2B platform for medical supplies,Mumbai,"Ackermans & van Haaren, HealthQuad, Rebright P...",Series B,"1,58,00,000",NaN
FinTech,37,04/09/2019,Cashflo,Invoice discounting platform and SME lending m...,Mumbai,SAIF Partners,Series A,"33,00,000",NaN
"Advertising, Marketing",38,04/09/2019,Digital F5,Digital marketing firm,Mumbai,TIW Private Equity,Private Equity Round,"60,00,000",NaN
...,...,...,...,...,...,...,...,...,...
NaN,3039,28/01/2015,Grabhouse.com,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,"25,00,000",Series A
NaN,3040,29/01/2015,Printvenue,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
NaN,3041,29/01/2015,Graphene,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
NaN,3042,30/01/2015,Mad Street Den,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
NaN,3043,30/01/2015,Simplotel,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"

In [77]:
a = ['Seed Round','Series A']
b = stp_df["InvestmentnType"].isin(a)
df2 = stp_df[b]
df2

,Sr No,Date dd/mm/yyyy,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
Industry Vertical,,,,,,,,,
Fashion and Apparel,5,02/01/2020,Fashor,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
Logistics,6,13/01/2020,Pando,"Open-market, freight management platform",Chennai,Chiratae Ventures,Series A,"90,00,000",NaN
Technology,8,12/12/2019,Ecozen,Agritech,Pune,Sathguru Catalyzer Advisors,Series A,"60,00,000",NaN
Video,15,14/12/2019,Trell,Experience Discovery Platform,Bengaluru,Ruizheng Investment,Seed Round,"20,00,000",NaN
Gaming,16,11/12/2019,Rein Games,Real money based gaming startup,Noida,Manipal Education and Medical Group (MEMG),Seed Round,"5,00,00,000",NaN
FinTech,37,04/09/2019,Cashflo,Invoice discounting platform and SME lending m...,Mumbai,SAIF Partners,Series A,"33,00,000",NaN
IoT,40,04/09/2019,75F,Building automation system,Burnsville,Breakthrough Energy Ventures,Series A,"1,80,00,000",NaN
Consumer Technology,42,04/09/2019,Atomberg Technology,"Consumer Electronics, Home Appliances",Mumbai,A91 Partners,Series A,"1,00,00,000",NaN
Accounting,44,03/09/2019,Vyapar App,Mobile-based Accounting Software,Bengaluru,"India Quotient, Axilor Ventures",Series A,"50,00,000",NaN
Finance,46,01/08/2019,Progcap,Supply Chain Management,New Delhi,Sequoia India,Series A,"50,00,000",NaN
Consumer Goods,54,23/08/2019,Lo! Foods,Low carb food for Diabetics,Bengaluru,"Rashmi Daga (founder, FreshMenu), Raveen Sastr...",Seed Round,"5,00,000",NaN
EdTech,58,23/08/2019,AdmitKard,University Admissions,Noida,Growth DNA,Seed Round,"10,00,000",NaN
Services,59,19/08/2019,Mishry Reviews,Product Review,Gurgaon,Vir Sanghvi,Series A,Undisclosed,NaN
Food and Beverage,67,04/07/2019,Daalchini Technologies,Digital Vending Machine,New Delhi,Artha Venture,Seed Round,"5,00,000",NaN
Health Care,72,10/07/2019,HealthAssure,Primary care medical network,Mumbai,Blume Ventures,Series A,"25,00,000",NaN
Luxury Label,73,09/07/2019,House of Msasaba,Clothes and Apparel,Mumbai,Binny Bansal,Series A,"10,00,000",NaN
Finance,78,03/06/2019,Avail Finance,FinTech,Bengaluru,Matrix Partners,Series A,"90,00,000",NaN
Energy,83,06/06/2019,Chakr Innovation,Renewable Energy,New Delhi,IAN Fund,Series A,"2,60,00,000",NaN
FinTech,86,10/06/2019,OkCredit,Financial Services,Haryana,Tiger Global Management,Series A,"1,55,00,000",NaN
Services,89,04/06/2019,Leegality,Digital Documentation,Mumbai/Bengaluru,Mumbai Angels,Series A,"34,00,000",NaN
Transport,90,06/05/2019,Ola Electric,Cabs,Bengaluru,Tata Sons,Series A,undisclosed,NaN
Agtech,96,28/05/2019,FreshVnF,Fresh Agriculture Produces,Mumbai,Equanimity Ventures,Seed Round,"14,00,00,000",NaN
Finance,99,16/04/2019,Kuvera,Wealth Management,Bengaluru,Eight Roads,Series A,"4,50,00,000",NaN
E-commerce,109,19/04/2019,My Healthcare,Software Solutions,Bengaluru and Gurugram,Sixth Sense Ventures,Series A,"30,00,000",NaN
Technology,112,17/04/2019,Increff,Supply-chain technology solutions,Bengaluru,"021 Capita, Binny Bansal",Series A,"30,00,000",NaN
Nanotechnology,115,13/02/2019,NanoClean Global,Anti-Pollution,New Delhi,"LetsVenture, PitchRight Venture, 91SpringBoard...",Series A,"6,00,000",NaN
"SaaS, Ecommerce",126,06/12/2018,BuildSupply,"Real Estate, ERP",Gurugram,"Venture Highway, GREE Ventures, Space Matrix, ...",Series A,"35,00,000",NaN
Gaming,130,08/11/2018,Mobile Premier League,Mobile e-Sports,Bengaluru,Undisclosed,Series A,"5,00,000",NaN
Food Tech,132,12/11/2018,Blackbuck,POS For Online Ordering,"New York, Bengaluru",Tiger Global,Series A,"10,00,000",NaN
Financial Tech,141,23/11/2018,Signzy,Digital Onboarding Solution,Mumbai/Bengaluru,Stellaris Venture Partners and Kalaari Capital...,Series A,"34,00,000",NaN
Software,142,24/11/2018,Engineer.ai,AI Platform,India/US,"Lakestar and Jungle Ventures, Softbank\\xe2\\x...",Series A,"2,95,00,000",NaN

In [78]:
u_values = pd.unique(stp_df['City  Location'])        # Displays Unique values
u_values

array(['Bengaluru', 'Gurgaon', 'New Delhi', 'Mumbai', 'Chennai', 'Pune',
       'Noida', 'Faridabad', 'San Francisco', 'San Jose,', 'Amritsar',
       'Delhi', 'Kormangala', 'Tulangan', 'Hyderabad', 'Burnsville',
       'Menlo Park', 'Gurugram', 'Palo Alto', 'Santa Monica', 'Singapore',
       'Taramani', 'Andheri', 'Chembur', 'Nairobi', 'Haryana', 'New York',
       'Karnataka', 'Mumbai/Bengaluru', 'Bhopal',
       'Bengaluru and Gurugram', 'India/Singapore', 'Jaipur', 'India/US',
       'Nagpur', 'Indore', 'New York, Bengaluru', 'California', 'India',
       'Ahemadabad', 'Rourkela', 'Srinagar', 'Bhubneswar', 'Chandigarh',
       'Delhi & Cambridge', 'Kolkatta', 'Kolkata', 'Coimbatore',
       'Bangalore', 'Udaipur', nan, 'Ahemdabad', 'Bhubaneswar',
       'Ahmedabad', 'Surat', 'Goa', 'Uttar Pradesh', 'Nw Delhi', 'Gaya',
       'Vadodara', 'Trivandrum', 'Missourie', 'Panaji', 'Gwalior',
       'Karur', 'Udupi', 'Kochi', 'Agra', 'Bangalore/ Bangkok', 'Hubli',
       'Kerala', 'Kozhikode', 'US', 'Siliguri', 'USA', 'Lucknow',
       'Kanpur', 'SFO / Bangalore', 'London', 'Seattle / Bangalore',
       'Pune/Seattle', 'Pune / Dubai', 'Bangalore / SFO', 'Varanasi',
       'New Delhi / US', 'Mumbai / UK', 'Jodhpur', 'Hyderabad/USA',
       'Boston', 'Bangalore / Palo Alto', 'Mumbai / NY', 'USA/India',
       'Goa/Hyderabad', 'Noida / Singapore', 'Belgaum', 'Pune / US',
       'Chennai/ Singapore', 'Pune / Singapore', 'Bangalore / San Mateo',
       'New York/ India', 'US/India', 'Gurgaon / SFO', 'Bangalore / USA',
       'New Delhi/ Houston', 'Mumbai / Global', 'India / US',
       '\\\\xc2\\\\xa0Noida', '\\\\xc2\\\\xa0Bangalore',
       '\\\\xc2\\\\xa0Gurgaon', '\\\\xc2\\\\xa0New Delhi',
       '\\\\xc2\\\\xa0Mumbai', 'New Delhi / California',
       'Dallas / Hyderabad'], dtype=object)

<h3 style = 'color : green'>SORTING</h3>

In [79]:
d2 = stp_df.sort_values(by = 'City  Location')
d2

,Sr No,Date dd/mm/yyyy,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
Industry Vertical,,,,,,,,,
eCommerce,1369,13/09/2016,ShoeKonnect,Footwear & Leather B2B App,Agra,Indian Angels Network,Seed Funding,NaN,NaN
eCommerce,1292,13/10/2016,Shoekonnect,B2B Marketplace for Shoes,Agra,Indian Angel Network,Seed Funding,NaN,NaN
Consumer Internet,179,16/08/2018,Enakshi,AI Based Solutions Platform,Ahemadabad,NaN,Seed/ Angel Funding,"1,14,811",NaN
E-Commerce,376,15/02/2018,Infibeam,Online Retailing,Ahemadabad,Network 18,Private Equity,"62,30,000",NaN
Consumer Internet,356,06/02/2018,Foodmemories,Online Food Marketplace,Ahemdabad,"Bhavesh Manglani, Suraj Saharan, Darshan Upadh...",Seed funding,NaN,NaN
...,...,...,...,...,...,...,...,...,...
NaN,3040,29/01/2015,Printvenue,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
NaN,3041,29/01/2015,Graphene,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
NaN,3042,30/01/2015,Mad Street Den,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
NaN,3043,30/01/2015,Simplotel,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
NaN,3044,31/01/2015,couponmachine.in,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

<h2 style = 'color : orange'>GROUPBY</h2>
-> It groups the values which are connected to each other.<br>
--> Groupby process:<br>
        1. Data acquire.<br>
        2. Splitting the data.<br>
        3. Appling operations(Aggregate operations).<br>
        4. Combined results<br>

In [80]:
p = ["Samsung", "Nokia", "Samsung", "Motorola", "Nokia", "Samsung", "Samsung"]
o = [2,4,3,4,6,7,3]

d = {
    "Product": p,
    "Orders":o
}

df1 = pd.DataFrame(d)
df1

    Product  Orders
0   Samsung       2
1     Nokia       4
2   Samsung       3
3  Motorola       4
4     Nokia       6
5   Samsung       7
6   Samsung       3

In [81]:
g = df1.groupby("Product")
print(g.sum())
print(g.mean())

          Orders
Product
Motorola       4
Nokia         10
Samsung       15
          Orders
Product
Motorola    4.00
Nokia       5.00
Samsung     3.75

In [82]:
invt = stp_df.groupby("InvestmentnType")
invt.size()

InvestmentnType
Angel                             1
Angel / Seed Funding              8
Angel Funding                     1
Angel Round                       1
Bridge Round                      1
Corporate Round                   2
Crowd Funding                     1
Crowd funding                     1
Debt                              1
Debt Funding                     25
Debt and Preference capital       1
Debt-Funding                      1
Equity                            2
Equity Based Funding              1
Funding Round                     1
Inhouse Funding                   1
Maiden Round                      1
Mezzanine                         1
Pre Series A                      1
Pre-Series A                      4
Pre-series A                      1
Private                           1
Private Equity                 1356
Private Equity Round              4
Private Funding                   1
PrivateEquity                     1
Private\\nEquity                  1
Seed                              4
Seed / Angel Funding             47
Seed / Angle Funding              3
Seed Funding                   1355
Seed Funding Round                1
Seed Round                        7
Seed funding                      1
Seed/ Angel Funding              60
Seed/Angel Funding               23
Seed\\nFunding                   30
Series A                         24
Series B                         20
Series B (Extension)              1
Series C                         14
Series D                         12
Series E                          2
Series F                          2
Series G                          1
Series H                          1
Series J                          1
Single Venture                    1
Structured Debt                   1
Term Loan                         1
Venture                           1
Venture - Series Unknown          1
Venture Round                     2
pre-Series A                      2
pre-series A                      1
dtype: int64

In [83]:
col = ["City  Location", "InvestmentnType"]           #IT gives output as Series
a = stp_df.groupby(col )["City  Location"]
b = a.sum()
print(b)

City  Location       InvestmentnType
Agra                 Seed Funding                                                    AgraAgra
Ahemadabad           Private Equity                                                Ahemadabad
                     Seed/ Angel Funding                                           Ahemadabad
Ahemdabad            Seed funding                                                   Ahemdabad
Ahmedabad            Debt Funding                                          AhmedabadAhmedabad
                                                                  ...
\\xc2\\xa0Gurgaon    Seed Funding           \\xc2\\xa0Gurgaon\\xc2\\xa0Gurgaon\\xc2\\xa0Gu...
\\xc2\\xa0Mumbai     Private Equity                                          \\xc2\\xa0Mumbai
\\xc2\\xa0New Delhi  Private Equity                                       \\xc2\\xa0New Delhi
                     Seed Funding                      \\xc2\\xa0New Delhi\\xc2\\xa0New Delhi
\\xc2\\xa0Noida      Private Equity                                           \\xc2\\xa0Noida
Name: City  Location, Length: 261, dtype: object

In [84]:
col = ["City  Location", "InvestmentnType"]           #IT gives output as DataFrame by using "as_index = False"
a = stp_df.groupby(col, as_index = False)["City  Location"]
b = a.sum()
print(b)

         InvestmentnType                                     City  Location
0           Seed Funding                                           AgraAgra
1         Private Equity                                         Ahemadabad
2    Seed/ Angel Funding                                         Ahemadabad
3           Seed funding                                          Ahemdabad
4           Debt Funding                                 AhmedabadAhmedabad
..                   ...                                                ...
256         Seed Funding  \\xc2\\xa0Gurgaon\\xc2\\xa0Gurgaon\\xc2\\xa0Gu...
257       Private Equity                                   \\xc2\\xa0Mumbai
258       Private Equity                                \\xc2\\xa0New Delhi
259         Seed Funding             \\xc2\\xa0New Delhi\\xc2\\xa0New Delhi
260       Private Equity                                    \\xc2\\xa0Noida

[261 rows x 2 columns]

In [85]:
stp_df.columns

Index(['Sr No', 'Date dd/mm/yyyy', 'Startup Name', 'SubVertical',
       'City  Location', 'Investors Name', 'InvestmentnType', 'Amount in USD',
       'Remarks'],
      dtype='object')

In [86]:
stp_df["Amount in USD"] = stp_df["Amount in USD"].str.replace(",","")
stp_df["Amount in USD"] = pd.to_numeric(stp_df["Amount in USD"], errors = 'coerce')
d = {"Amount in USD":sum}
col = ['Date dd/mm/yyyy', 'City  Location']
p = stp_df.groupby(col)
b = p.agg(d)
print(b)

                                         Amount in USD
Date dd/mm/yyyy     City  Location
01/01/2016          Mumbai                         0.0
                    New Delhi                      0.0
01/02/2016          New Delhi                      0.0
01/02/2018          Bengaluru              300000000.0
                    Gurugram               200000000.0
...                                                ...
31/10/2015          Chandigarh              10000000.0
31/10/2016          Mumbai                   1000000.0
31/10/2017          Chennai                 14000000.0
                    Mumbai                  32000000.0
\\xc2\\xa010/7/2015 \\xc2\\xa0New Delhi            0.0

[2262 rows x 1 columns]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_17892\2919135835.py:6: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  b = p.agg(d)

<h2>MERGING AND JOINING</h2>
-->pd.merge(p1,p2,p3,p4) is used to merge two dataframes.<br>
1. Here "p1" parameter refers to dataframe1.<br>
2. Here "p2" parameter refers to dataframe2.<br>
3. Here "p3" parameter refers to common column in both dataframes.<br>
4. Here "p4" parameter refers to type of join or merging we are going to use.<br>

In [87]:
d1 = {
    "Id":[1, 2, 3, 4, 5, 6],
    "Name":["Prasad", "Venu", "Madhu", "Naresh", "Sai", "Veeru"],
    "Subject":["English", "Java", "Html", "Python", "C", "Dot net"]
}

d2 = {
    "Id":[11, 12, 13, 14, 15, 16],
    "Name":["Srinu", "Sumanth", "Neel", "Daniel", "Arjun", "Veeru"],
    "Subject":["Java", "Html", "Cpp", "Python", "C", "Dot net"]
}

df1 = DataFrame(d1)
df2 = DataFrame(d2)

print(df1)
print(df2)

   Id    Name  Subject
0   1  Prasad  English
1   2    Venu     Java
2   3   Madhu     Html
3   4  Naresh   Python
4   5     Sai        C
5   6   Veeru  Dot net
   Id     Name  Subject
0  11    Srinu     Java
1  12  Sumanth     Html
2  13     Neel      Cpp
3  14   Daniel   Python
4  15    Arjun        C
5  16    Veeru  Dot net

In [88]:
inner_join = pd.merge(df1, df2, on = "Subject", how = "inner")
inner_join

   Id_x  Name_x  Subject  Id_y   Name_y
0     2    Venu     Java    11    Srinu
1     3   Madhu     Html    12  Sumanth
2     4  Naresh   Python    14   Daniel
3     5     Sai        C    15    Arjun
4     6   Veeru  Dot net    16    Veeru

In [89]:
left_join = pd.merge(df1, df2, on = "Subject", how = "left")
left_join

   Id_x  Name_x  Subject  Id_y   Name_y
0     1  Prasad  English   NaN      NaN
1     2    Venu     Java  11.0    Srinu
2     3   Madhu     Html  12.0  Sumanth
3     4  Naresh   Python  14.0   Daniel
4     5     Sai        C  15.0    Arjun
5     6   Veeru  Dot net  16.0    Veeru

In [90]:
right_join = pd.merge(df1, df2, on = "Subject", how = "right")
right_join

   Id_x  Name_x  Subject  Id_y   Name_y
0   2.0    Venu     Java    11    Srinu
1   3.0   Madhu     Html    12  Sumanth
2   NaN     NaN      Cpp    13     Neel
3   4.0  Naresh   Python    14   Daniel
4   5.0     Sai        C    15    Arjun
5   6.0   Veeru  Dot net    16    Veeru

In [91]:
outer_join = pd.merge(df1, df2, on = "Subject", how = "outer")
outer_join

   Id_x  Name_x  Subject  Id_y   Name_y
0   5.0     Sai        C  15.0    Arjun
1   NaN     NaN      Cpp  13.0     Neel
2   6.0   Veeru  Dot net  16.0    Veeru
3   1.0  Prasad  English   NaN      NaN
4   3.0   Madhu     Html  12.0  Sumanth
5   2.0    Venu     Java  11.0    Srinu
6   4.0  Naresh   Python  14.0   Daniel

<h2 style = "color : orange">CONCAT</h2>
--> It is used to add two dataframes with same columns.<br>
--> It adds the two datafames next to each other.<br>
--> It takes list as a parameter.<br>
--> pd.concat(p), "p" is list dataframe.<br>

In [92]:
l1 = [[11,22],[33,44]]
l2 = [[55,66],[77,88]]
c = ["a","b"]
df1 = DataFrame(l1, columns = c)
df2 = DataFrame(l2, columns = c)
print(df1)
print()
print(df2)
con = pd.concat([df1,df2])
print(con)

    a   b
0  11  22
1  33  44

    a   b
0  55  66
1  77  88
    a   b
0  11  22
1  33  44
0  55  66
1  77  88

In [93]:
con = pd.concat([df1,df2], ignore_index = True)
print(con)

    a   b
0  11  22
1  33  44
2  55  66
3  77  88

In [94]:
d1 = {
    "Id":[1, 2, 3, 4, 5, 6],                                              #If the columns names are not same then it gives additional columns.
    "Name":["Prasad", "Venu", "Madhu", "Naresh", "Sai", "Veeru"],
    "Subject":["English", "Java", "Html", "Python", "C", "Dot net"]
}

d2 = {
    "Id":[11, 12, 13, 14, 15, 16],
    "Names":["Srinu", "Sumanth", "Neel", "Daniel", "Arjun", "Veeru"],
    "Subject":["Java", "Html", "Cpp", "Python", "C", "Dot net"]
}

df1 = DataFrame(d1)
df2 = DataFrame(d2)

n = [df1, df2]
df3 = pd.concat(n)
df3

   Id    Name  Subject    Names
0   1  Prasad  English      NaN
1   2    Venu     Java      NaN
2   3   Madhu     Html      NaN
3   4  Naresh   Python      NaN
4   5     Sai        C      NaN
5   6   Veeru  Dot net      NaN
0  11     NaN     Java    Srinu
1  12     NaN     Html  Sumanth
2  13     NaN      Cpp     Neel
3  14     NaN   Python   Daniel
4  15     NaN        C    Arjun
5  16     NaN  Dot net    Veeru

In [95]:
n = [df1, df2]                                        #Here we use axis to level up to clear nan values and the dataframe attached side by another .
df3 = pd.concat(n, axis = 1)
df3

   Id    Name  Subject  Id    Names  Subject
0   1  Prasad  English  11    Srinu     Java
1   2    Venu     Java  12  Sumanth     Html
2   3   Madhu     Html  13     Neel      Cpp
3   4  Naresh   Python  14   Daniel   Python
4   5     Sai        C  15    Arjun        C
5   6   Veeru  Dot net  16    Veeru  Dot net

<h2>Pandas - DataFrame  Adding, Dropping Rows & columns </h2>

In [96]:
lis1 = [[192837, "Veeru", 3, "LG Mobile", 65999, 1],
        [192838,"neelima", 19, "Apple ipad 10.2-inch", 63000, 2],
        [192839, "Balaji", 12, "34in Ultrawide Monitor", 75999,1],
        [192840,"Sai", 20, "iPhone", 60000, 2],
        [192841, "Vinay", 10, "Bose SoundSport Headphones", 69999, 3]]
c = ["Order_Id", "Customer_name", "Customer_Id", "Product_name", "Product_cost", "Quantity"]
df1 = DataFrame(lis1, columns = c)
df1

,Order_Id,Customer_name,Customer_Id,Product_name,Product_cost,Quantity
0,192837,Veeru,3,LG Mobile,65999,1
1,192838,neelima,19,Apple ipad 10.2-inch,63000,2
2,192839,Balaji,12,34in Ultrawide Monitor,75999,1
3,192840,Sai,20,iPhone,60000,2
4,192841,Vinay,10,Bose SoundSport Headphones,69999,3

In [97]:
df1["Total_cost"] = df1["Product_cost"] * df1["Quantity"]        # Adding new columns
df1

,Order_Id,Customer_name,Customer_Id,Product_name,Product_cost,Quantity,Total_cost
0,192837,Veeru,3,LG Mobile,65999,1,65999
1,192838,neelima,19,Apple ipad 10.2-inch,63000,2,126000
2,192839,Balaji,12,34in Ultrawide Monitor,75999,1,75999
3,192840,Sai,20,iPhone,60000,2,120000
4,192841,Vinay,10,Bose SoundSport Headphones,69999,3,209997

In [98]:
c = df1["Product_cost"] + df1["Quantity"]     # Inserting columns in a precise position or desired position.
df1.insert(5, "Tl", c)
df1

,Order_Id,Customer_name,Customer_Id,Product_name,Product_cost,Tl,Quantity,Total_cost
0,192837,Veeru,3,LG Mobile,65999,66000,1,65999
1,192838,neelima,19,Apple ipad 10.2-inch,63000,63002,2,126000
2,192839,Balaji,12,34in Ultrawide Monitor,75999,76000,1,75999
3,192840,Sai,20,iPhone,60000,60002,2,120000
4,192841,Vinay,10,Bose SoundSport Headphones,69999,70002,3,209997

In [99]:
df1.drop(columns = "Tl", inplace = True)      # Dropping a column.
df1

,Order_Id,Customer_name,Customer_Id,Product_name,Product_cost,Quantity,Total_cost
0,192837,Veeru,3,LG Mobile,65999,1,65999
1,192838,neelima,19,Apple ipad 10.2-inch,63000,2,126000
2,192839,Balaji,12,34in Ultrawide Monitor,75999,1,75999
3,192840,Sai,20,iPhone,60000,2,120000
4,192841,Vinay,10,Bose SoundSport Headphones,69999,3,209997

In [100]:
df1.drop(3,axis = 0)      # Droping a row using index

,Order_Id,Customer_name,Customer_Id,Product_name,Product_cost,Quantity,Total_cost
0,192837,Veeru,3,LG Mobile,65999,1,65999
1,192838,neelima,19,Apple ipad 10.2-inch,63000,2,126000
2,192839,Balaji,12,34in Ultrawide Monitor,75999,1,75999
4,192841,Vinay,10,Bose SoundSport Headphones,69999,3,209997

In [101]:
new = [192842, "Vijay", 5, "Rolex Watch", 2000000,2,4000000]    # Adding new row to the dataframe.
df1.loc[len(df1)] = new
df1

,Order_Id,Customer_name,Customer_Id,Product_name,Product_cost,Quantity,Total_cost
0,192837,Veeru,3,LG Mobile,65999,1,65999
1,192838,neelima,19,Apple ipad 10.2-inch,63000,2,126000
2,192839,Balaji,12,34in Ultrawide Monitor,75999,1,75999
3,192840,Sai,20,iPhone,60000,2,120000
4,192841,Vinay,10,Bose SoundSport Headphones,69999,3,209997
5,192842,Vijay,5,Rolex Watch,2000000,2,4000000

 <h2 style = "color : orange">Pandas - DataFrame - Data time</h2>
 --> We use "parse_dates = [column_name]" when we import the data/file.<br> 
 --> suppose, If it is not working then we have to do it manually.<br>
 --> "df[column_name] = pd.to_datetime(df[column_name], format = '%d%m%Y / %m%d%Y / %Y%m%d')" is used after loading the data.
 If it has a string value such as 12sep2019 we have to use format = '%d%b%Y.'<br>
 --> If we have any irrelevent errors then we use errors = 'coerce' then it converts the errors as "NaT"(Not A Time).<br>

In [102]:
sdf = pd.read_csv( "D:\Datasets\startup_funding.csv",
                  parse_dates = ['Date dd/mm/yyyy'])
modified_col = {'Sr No': 'Sl_no',
                'Date dd/mm/yyyy':'Date',
                'Startup Name':'Startup_name',
                'Industry Vertical':'Industry_Vertical',
                'City  Location':'Location',
                'Investors Name':'Investors',
                'InvestmentnType':'Fund_Type',
                'Amount in USD':'Funding'}
sdf.rename(columns = modified_col, inplace = True)

In [103]:
sdf.columns

Index(['Sl_no', 'Date', 'Startup_name', 'Industry_Vertical', 'SubVertical',
       'Location', 'Investors', 'Fund_Type', 'Funding', 'Remarks'],
      dtype='object')

In [104]:
sdf["Date"] = sdf["Date"].str.replace("\xa0", "", regex = False).str.strip()     #After cleaning date column we convert it manually.

sdf["Date"] = pd.to_datetime(sdf["Date"], dayfirst = True, errors = "coerce")
sdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sl_no              3044 non-null   int64
 1   Date               3036 non-null   datetime64[ns]
 2   Startup_name       3044 non-null   object
 3   Industry_Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   Location           2864 non-null   object
 6   Investors          3020 non-null   object
 7   Fund_Type          3040 non-null   object
 8   Funding            2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 237.9+ KB

In [105]:
sdf1 = sdf.set_index("Date").sort_index()
sdf1.tail(10)

,Sl_no,Startup_name,Industry_Vertical,SubVertical,Location,Investors,Fund_Type,Funding,Remarks
Date,,,,,,,,,
2020-01-13,6,Pando,Logistics,"Open-market, freight management platform",Chennai,Chiratae Ventures,Series A,"90,00,000",NaN
2020-01-13,2,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
NaT,193,Loan Tap,Consumer Internet,Online Lending Platform For Salaried Professio...,Mumbai,"Shunwei Capital, Tuscan Ventures, Ashish Goenk...",Private Equity,"62,50,000",NaN
NaT,2572,HandyHome,Hyperlocal Electronics repair Service,NaN,Mumbai,"Bessemer Ventures, Kae Capital",Seed Funding,"6,30,000",NaN
NaT,2607,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,"\\xc2\\xa0600,000",NaN
NaT,2776,Mobiefit,Mobile Fitness App,NaN,Goa,Prototyze,Seed Funding,NaN,NaN
NaT,2777,Plancess,Online Education Platform,NaN,Mumbai,"Rajendra Gogri,\\xc2\\xa0 Chandrakant Gogri",Seed Funding,"20,00,000",NaN
NaT,2832,The Porter,Logistics Tech,NaN,Mumbai,Kae Capital,Seed Funding,"5,00,000",NaN
NaT,3012,Wishberry,NaN,NaN,NaN,"Rajan Anandan, Shankar Mahadevan, Deep Kalra &...",Seed Funding,"6,50,000",NaN
NaT,3030,Corporate360,NaN,NaN,NaN,Group of Angel Investors,Seed Funding,"2,00,000",NaN

In [106]:
data = {
    "Product":["Samsung", "iPhone", "Motorola"],
    "Status":["Success", "Success", "Failed"],
    "Cost":[10000, 50000, 15000],
    "PurDate":['02092019', '13092019', '21092019']
}
df = DataFrame(data)
df['PurDate'] = pd.to_datetime(df["PurDate"], format = "%d%m%Y")
print(df.info())
print()
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  3 non-null      object
 1   Status   3 non-null      object
 2   Cost     3 non-null      int64
 3   PurDate  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 228.0+ bytes
None

    Product   Status   Cost    PurDate
0   Samsung  Success  10000 2019-09-02
1    iPhone  Success  50000 2019-09-13
2  Motorola   Failed  15000 2019-09-21

In [107]:
data = {
    "Product":["Samsung", "iPhone", "Motorola"],
    "Status":["Success", "Success", "Failed"],
    "Cost":[10000, 50000, 15000],
    "PurDate":['02Sep2019', '13Sep2019', '21Sep2019']
}
df = DataFrame(data)
print(df)
print()
df['PurDate'] = pd.to_datetime(df['PurDate'])
print(df)

    Product   Status   Cost    PurDate
0   Samsung  Success  10000  02Sep2019
1    iPhone  Success  50000  13Sep2019
2  Motorola   Failed  15000  21Sep2019

    Product   Status   Cost    PurDate
0   Samsung  Success  10000 2019-09-02
1    iPhone  Success  50000 2019-09-13
2  Motorola   Failed  15000 2019-09-21

In [108]:
df['PurDate'].dt.day                         #To see the day seperately from the date column

0     2
1    13
2    21
Name: PurDate, dtype: int32

In [109]:
df['PurDate'].dt.month                         #To see the month seperately from the date column

0    9
1    9
2    9
Name: PurDate, dtype: int32

In [110]:
df['PurDate'].dt.year                         #To see the year seperately from the date column

0    2019
1    2019
2    2019
Name: PurDate, dtype: int32

In [111]:
print(df['PurDate'].dt.day_name())

0      Monday
1      Friday
2    Saturday
Name: PurDate, dtype: object

In [112]:
df["PurDate"].dt.weekday+1

0    1
1    5
2    6
Name: PurDate, dtype: int32

<h2>Concatinating Multiple  CSV Files </h2>

In [126]:
import os 
                                                                    #Validating file path and filtering csv files in the folder
path = "D:\Datasets\monthly_sales"
files = os.listdir(path)
file = [f1  for f1 in files  if f1.endswith(".csv")]
files

['sales_2025_01.csv',
 'sales_2025_02.csv',
 'sales_2025_03.csv',
 'sales_2025_04.csv',
 'sales_2025_05.csv',
 'sales_2025_06.csv',
 'sales_2025_07.csv',
 'sales_2025_08.csv',
 'sales_2025_09.csv',
 'sales_2025_10.csv',
 'sales_2025_11.csv',
 'sales_2025_12.csv']

In [127]:
import os 
import glob
path = "D:\Datasets\monthly_sales"                       #By using "glob" module we are creating the seperate paths to files
paths = os.path.join(path,"*.csv")
files = glob.glob(paths)
files

['D:\\Datasets\\monthly_sales\\sales_2025_01.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_02.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_03.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_04.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_05.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_06.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_07.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_08.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_09.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_10.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_11.csv',
 'D:\\Datasets\\monthly_sales\\sales_2025_12.csv']

In [144]:
result = [pd.read_csv(file) for file in files]               #Converting all the csv files into dataframe in a list
print(type(result))

sales_df = pd.concat(result, ignore_index = True)            #concatinating all the dataframes in the list
print(sales_df)
sales_df.to_csv("year_sales")

<class 'list'>
      Order_ID        Date   Product Region Salesperson  Quantity  Unit_Price  \
0    202501001  2025-01-02  Keyboard   West        Amit         1       11012
1    202501002  2025-01-03   Monitor   West       Divya         8       27300
2    202501003  2025-01-27    Tablet   West      Anjali         5       27701
3    202501004  2025-01-12    Tablet   East      Anjali        15       32530
4    202501005  2025-01-26    Laptop  South        Amit        15       37780
..         ...         ...       ...    ...         ...       ...         ...
143  202512009  2025-12-18   Printer   East        Ravi         8       18656
144  202512010  2025-12-26    Mobile   West       Sneha        17        6531
145  202512011  2025-12-08     Mouse   West       Divya         5       18463
146  202512012  2025-12-12    Tablet   East        Amit        19       33301
147  202512013  2025-12-20   Monitor  North       Sneha         7       48938

     Total_Sales
0          11012
1         218400
2         138505
3         487950
4         566700
..           ...
143       149248
144       111027
145        92315
146       632719
147       342566

[148 rows x 8 columns]

In [143]:
gener = (pd.read_csv(file) for file in files)
print(type(gener))
sales_df1 = pd.concat(gener, ignore_index = True)
print(sales_df1.head(15))
sales_df1.to_csv("Annual_sales")

<class 'generator'>
     Order_ID        Date     Product Region Salesperson  Quantity  \
0   202501001  2025-01-02    Keyboard   West        Amit         1
1   202501002  2025-01-03     Monitor   West       Divya         8
2   202501003  2025-01-27      Tablet   West      Anjali         5
3   202501004  2025-01-12      Tablet   East      Anjali        15
4   202501005  2025-01-26      Laptop  South        Amit        15
5   202501006  2025-01-05     Printer   East       Sneha         2
6   202501007  2025-01-19     Printer  South        Ravi         3
7   202501008  2025-01-06       Mouse   West       Sneha        10
8   202501009  2025-01-22      Laptop   East       Divya         3
9   202501010  2025-01-20      Laptop   West      Anjali         6
10  202501011  2025-01-28     Monitor  South       Sneha         8
11  202501012  2025-01-24  Headphones  South       Divya        12
12  202501013  2025-01-20     Printer  South       Divya         9
13  202502001  2025-02-10    Keyboard  South       Priya        10
14  202502002  2025-02-06      Tablet   East        Amit        11

    Unit_Price  Total_Sales
0        11012        11012
1        27300       218400
2        27701       138505
3        32530       487950
4        37780       566700
5        19222        38444
6        31652        94956
7        24845       248450
8        34494       103482
9         1387         8322
10       37790       302320
11       11177       134124
12       11364       102276
13       39471       394710
14       40120       441320